/**
 * SPDX-FileCopyrightText: (c) 2024 Liferay, Inc. https://liferay.com
 * SPDX-License-Identifier: LGPL-2.1-or-later OR LicenseRef-Liferay-DXP-EULA-2.0.0-2023-06
 */

package com.liferay.contact.management.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the ContactEntry service. Represents a row in the &quot;CTMG_ContactEntry&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>com.liferay.contact.management.model.impl.ContactEntryModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>com.liferay.contact.management.model.impl.ContactEntryImpl</code>.
 * </p>
 *
 * @author Rubens Soares
 * @see ContactEntry
 * @generated
 */
@ProviderType
public interface ContactEntryModel extends BaseModel<ContactEntry> {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a contact entry model instance should use the {@link ContactEntry} interface instead.
	 */

	/**
	 * Returns the primary key of this contact entry.
	 *
	 * @return the primary key of this contact entry
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this contact entry.
	 *
	 * @param primaryKey the primary key of this contact entry
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the entry ID of this contact entry.
	 *
	 * @return the entry ID of this contact entry
	 */
	public long getEntryId();

	/**
	 * Sets the entry ID of this contact entry.
	 *
	 * @param entryId the entry ID of this contact entry
	 */
	public void setEntryId(long entryId);

	/**
	 * Returns the family relationship of this contact entry.
	 *
	 * @return the family relationship of this contact entry
	 */
	@AutoEscape
	public String getFamilyRelationship();

	/**
	 * Sets the family relationship of this contact entry.
	 *
	 * @param familyRelationship the family relationship of this contact entry
	 */
	public void setFamilyRelationship(String familyRelationship);

	/**
	 * Returns the phone of this contact entry.
	 *
	 * @return the phone of this contact entry
	 */
	public long getPhone();

	/**
	 * Sets the phone of this contact entry.
	 *
	 * @param phone the phone of this contact entry
	 */
	public void setPhone(long phone);

	/**
	 * Returns the address of this contact entry.
	 *
	 * @return the address of this contact entry
	 */
	@AutoEscape
	public String getAddress();

	/**
	 * Sets the address of this contact entry.
	 *
	 * @param address the address of this contact entry
	 */
	public void setAddress(String address);

	/**
	 * Returns the contact ID of this contact entry.
	 *
	 * @return the contact ID of this contact entry
	 */
	public long getContactId();

	/**
	 * Sets the contact ID of this contact entry.
	 *
	 * @param contactId the contact ID of this contact entry
	 */
	public void setContactId(long contactId);

	@Override
	public ContactEntry cloneWithOriginalValues();

	public default String toXmlString() {
		return null;
	}

}