components:
    schemas:
        Contact:
            properties:
                contactId:
                    type: integer
                name:
                    type: string
                email:
                    type: string
                phone:
                    type: integer
                address:
                    type: string
            type: object
        ContactEntry:
            properties:
                entryId:
                    type: integer
                familyRelationship:
                    type: string
                phone:
                    type: integer
                address:
                    type: string
                contactId:
                    type: integer
            type: object
info:
    description: "Contact REST API"
    license:
        name: "Apache 2.0"
        url: "http://www.apache.org/licenses/LICENSE-2.0.html"
    title: "Contact Rest Api"
    version: v1.0
openapi: 3.0.1
paths:
    "/contact":
        get:
            operationId: getContact
            responses:
                200:
                    content:
                        application/json:
                            schema:
                                items:
                                    $ref: "#/components/schemas/Contact"
                                type: array
                        application/xml:
                            schema:
                                items:
                                    $ref: "#/components/schemas/Contact"
                                type: array
            tags: ["Contact"]
        post:
            operationId: postContact
            requestBody:
                content:
                    application/json:
                        schema:
                            $ref: "#/components/schemas/Contact"
                    application/xml:
                        schema:
                            $ref: "#/components/schemas/Contact"
            responses:
                200:
                    content:
                        application/json:
                            schema:
                                $ref: "#/components/schemas/Contact"
                        application/xml:
                            schema:
                                $ref: "#/components/schemas/Contact"
            tags: ["Contact"]
    "/contact/{contactId}":
        delete:
            operationId: deleteContact
            parameters:
                - in: path
                  name: contactId
                  required: true
                  schema:
                      type: integer
            responses:
                204:
                    content:
                        application/json: {}
                        application/xml: {}
            tags: ["Contact"]
        get:
            operationId: getIdContact
            parameters:
                - in: path
                  name: contactId
                  required: true
                  schema:
                      type: integer
            responses:
                200:
                    content:
                        application/json:
                            schema:
                                $ref: "#/components/schemas/Contact"
                        application/xml:
                            schema:
                                $ref: "#/components/schemas/Contact"
            tags: ["Contact"]
        put:
            operationId: putContact
            parameters:
                - in: path
                  name: contactId
                  required: true
                  schema:
                      type: integer
            requestBody:
                content:
                    application/json:
                        schema:
                            $ref: "#/components/schemas/Contact"
                    application/xml:
                        schema:
                            $ref: "#/components/schemas/Contact"
            responses:
                200:
                    content:
                        application/json:
                            schema:
                                $ref: "#/components/schemas/Contact"
                        application/xml:
                            schema:
                                $ref: "#/components/schemas/Contact"
            tags: ["Contact"]
    "/contact/{contactId}/contactEntry":
        get:
            operationId: getContactEntries
            parameters:
                - in: path
                  name: contactId
                  required: true
                  schema:
                      type: integer
            responses:
                200:
                    content:
                        application/json:
                            schema:
                                items:
                                    $ref: "#/components/schemas/ContactEntry"
                                type: array
                        application/xml:
                            schema:
                                items:
                                    $ref: "#/components/schemas/ContactEntry"
                                type: array
            tags: ["ContactEntry"]
        post:
            operationId: postContactEntry
            parameters:
                - in: path
                  name: contactId
                  required: true
                  schema:
                      type: integer
            requestBody:
                content:
                    application/json:
                            schema:
                                $ref: "#/components/schemas/ContactEntry"
                    application/xml:
                            schema:
                                $ref: "#/components/schemas/ContactEntry"
            responses:
                200:
                    content:
                        application/json:
                            schema:
                                $ref: "#/components/schemas/ContactEntry"
                        application/xml:
                            schema:
                                $ref: "#/components/schemas/ContactEntry"
            tags: ["ContactEntry"]
    "/contactEntry/{entryId}":
        delete:
            operationId: deleteContactEntry
            parameters:
                - in: path
                  name: entryId
                  required: true
                  schema:
                      type: integer
            responses:
                204:
                    content:
                        application/json: {}
                        application/xml: {}
            tags: ["ContactEntry"]
        get:
            operationId: getContactEntryId
            parameters:
                - in: path
                  name: entryId
                  required: true
                  schema:
                      type: integer
            responses:
                200:
                    content:
                        application/json:
                            schema:
                                $ref: "#/components/schemas/ContactEntry"
                        application/xml:
                            schema:
                                $ref: "#/components/schemas/ContactEntry"
            tags: ["ContactEntry"] 
        put:
            operationId: putContactEntry
            parameters:
                - in: path
                  name: entryId
                  required: true
                  schema:
                      type: integer
            requestBody:
                content:
                    application/json:
                        schema:
                            $ref: "#/components/schemas/ContactEntry"
                    application/xml:
                        schema:
                            $ref: "#/components/schemas/ContactEntry"
            responses:
                200:
                    content:
                        application/json:
                            schema:
                                $ref: "#/components/schemas/ContactEntry"
                        application/xml:
                            schema:
                                $ref: "#/components/schemas/ContactEntry"
            tags: ["ContactEntry"]

                


