components:
    schemas:
        Contact:
            properties:
                contactId:
                    type: integer
                name:
                    type: string
                email:
                    type: string
                phone:
                    type: integer
                address:
                    type: string
            type: object
info:
    description: "Contact REST API"
    license:
        name: "Apache 2.0"
        url: "http://www.apache.org/licenses/LICENSE-2.0.html"
    title: "Contact Rest Api"
    version: v1.0
openapi: 3.0.1
paths:
    "/contact":
        get:
            operationId: getContact
            responses:
                200:
                    content:
                        application/json:
                            schema:
                                items:
                                    $ref: "#/components/schemas/Contact"
                                type: array
                        application/xml:
                            schema:
                                items:
                                    $ref: "#/components/schemas/Contact"
                                type: array
            tags: ["Contact"]
                        
