/**
 * SPDX-FileCopyrightText: (c) 2024 Liferay, Inc. https://liferay.com
 * SPDX-License-Identifier: LGPL-2.1-or-later OR LicenseRef-Liferay-DXP-EULA-2.0.0-2023-06
 */

package com.liferay.contact.management.model.impl;

import com.liferay.contact.management.model.ContactEntry;
import com.liferay.contact.management.service.ContactEntryLocalServiceUtil;

/**
 * The extended model base implementation for the ContactEntry service. Represents a row in the &quot;CTMG_ContactEntry&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This class exists only as a container for the default extended model level methods generated by ServiceBuilder. Helper methods and all application logic should be put in {@link ContactEntryImpl}.
 * </p>
 *
 * @author Rubens Soares
 * @see ContactEntryImpl
 * @see ContactEntry
 * @generated
 */
public abstract class ContactEntryBaseImpl
	extends ContactEntryModelImpl implements ContactEntry {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a contact entry model instance should use the <code>ContactEntry</code> interface instead.
	 */
	@Override
	public void persist() {
		if (this.isNew()) {
			ContactEntryLocalServiceUtil.addContactEntry(this);
		}
		else {
			ContactEntryLocalServiceUtil.updateContactEntry(this);
		}
	}

}